<?php

// Data functions (insert, update, delete, form) for table books

// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

function books_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('books');
	if(!$arrPerm[1]){
		return false;
	}

	$data['ISBN_NO'] = makeSafe($_REQUEST['ISBN_NO']);
		if($data['ISBN_NO'] == empty_lookup_value){ $data['ISBN_NO'] = ''; }
	$data['Book_Title'] = makeSafe($_REQUEST['Book_Title']);
		if($data['Book_Title'] == empty_lookup_value){ $data['Book_Title'] = ''; }
	$data['Book_Type'] = makeSafe($_REQUEST['Book_Type']);
		if($data['Book_Type'] == empty_lookup_value){ $data['Book_Type'] = ''; }
	$data['Author_Name'] = makeSafe($_REQUEST['Author_Name']);
		if($data['Author_Name'] == empty_lookup_value){ $data['Author_Name'] = ''; }
	$data['Quantity'] = makeSafe($_REQUEST['Quantity']);
		if($data['Quantity'] == empty_lookup_value){ $data['Quantity'] = ''; }
	$data['Purchase_Date'] = intval($_REQUEST['Purchase_DateYear']) . '-' . intval($_REQUEST['Purchase_DateMonth']) . '-' . intval($_REQUEST['Purchase_DateDay']);
	$data['Purchase_Date'] = parseMySQLDate($data['Purchase_Date'], '1');
	$data['Edition'] = makeSafe($_REQUEST['Edition']);
		if($data['Edition'] == empty_lookup_value){ $data['Edition'] = ''; }
	$data['Price'] = makeSafe($_REQUEST['Price']);
		if($data['Price'] == empty_lookup_value){ $data['Price'] = ''; }
	$data['Pages'] = makeSafe($_REQUEST['Pages']);
		if($data['Pages'] == empty_lookup_value){ $data['Pages'] = ''; }
	$data['Publisher'] = makeSafe($_REQUEST['Publisher']);
		if($data['Publisher'] == empty_lookup_value){ $data['Publisher'] = ''; }
	if($data['Price'] == '') $data['Price'] = "0.00";

	// hook: books_before_insert
	if(function_exists('books_before_insert')){
		$args=array();
		if(!books_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `books` set       `ISBN_NO`=' . (($data['ISBN_NO'] !== '' && $data['ISBN_NO'] !== NULL) ? "'{$data['ISBN_NO']}'" : 'NULL') . ', `Book_Title`=' . (($data['Book_Title'] !== '' && $data['Book_Title'] !== NULL) ? "'{$data['Book_Title']}'" : 'NULL') . ', `Book_Type`=' . (($data['Book_Type'] !== '' && $data['Book_Type'] !== NULL) ? "'{$data['Book_Type']}'" : 'NULL') . ', `Author_Name`=' . (($data['Author_Name'] !== '' && $data['Author_Name'] !== NULL) ? "'{$data['Author_Name']}'" : 'NULL') . ', `Quantity`=' . (($data['Quantity'] !== '' && $data['Quantity'] !== NULL) ? "'{$data['Quantity']}'" : 'NULL') . ', `Purchase_Date`=' . (($data['Purchase_Date'] !== '' && $data['Purchase_Date'] !== NULL) ? "'{$data['Purchase_Date']}'" : 'NULL') . ', `Edition`=' . (($data['Edition'] !== '' && $data['Edition'] !== NULL) ? "'{$data['Edition']}'" : 'NULL') . ', `Price`=' . (($data['Price'] !== '' && $data['Price'] !== NULL) ? "'{$data['Price']}'" : 'NULL') . ', `Pages`=' . (($data['Pages'] !== '' && $data['Pages'] !== NULL) ? "'{$data['Pages']}'" : 'NULL') . ', `Publisher`=' . (($data['Publisher'] !== '' && $data['Publisher'] !== NULL) ? "'{$data['Publisher']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"books_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: books_after_insert
	if(function_exists('books_after_insert')){
		$res = sql("select * from `books` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!books_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('books', $recID, getLoggedMemberID());

	return $recID;
}

function books_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('books');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='books' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='books' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: books_before_delete
	if(function_exists('books_before_delete')){
		$args=array();
		if(!books_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: Book_Issue
	$res = sql("select `id` from `books` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `Book_Issue` where `Book_Number`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Book_Issue", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Book_Issue", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='books_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='books_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `books` where `id`='$selected_id'", $eo);

	// hook: books_after_delete
	if(function_exists('books_after_delete')){
		$args=array();
		books_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='books' and pkValue='$selected_id'", $eo);
}

function books_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('books');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='books' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='books' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['ISBN_NO'] = makeSafe($_REQUEST['ISBN_NO']);
		if($data['ISBN_NO'] == empty_lookup_value){ $data['ISBN_NO'] = ''; }
	$data['Book_Title'] = makeSafe($_REQUEST['Book_Title']);
		if($data['Book_Title'] == empty_lookup_value){ $data['Book_Title'] = ''; }
	$data['Book_Type'] = makeSafe($_REQUEST['Book_Type']);
		if($data['Book_Type'] == empty_lookup_value){ $data['Book_Type'] = ''; }
	$data['Author_Name'] = makeSafe($_REQUEST['Author_Name']);
		if($data['Author_Name'] == empty_lookup_value){ $data['Author_Name'] = ''; }
	$data['Quantity'] = makeSafe($_REQUEST['Quantity']);
		if($data['Quantity'] == empty_lookup_value){ $data['Quantity'] = ''; }
	$data['Purchase_Date'] = intval($_REQUEST['Purchase_DateYear']) . '-' . intval($_REQUEST['Purchase_DateMonth']) . '-' . intval($_REQUEST['Purchase_DateDay']);
	$data['Purchase_Date'] = parseMySQLDate($data['Purchase_Date'], '1');
	$data['Edition'] = makeSafe($_REQUEST['Edition']);
		if($data['Edition'] == empty_lookup_value){ $data['Edition'] = ''; }
	$data['Price'] = makeSafe($_REQUEST['Price']);
		if($data['Price'] == empty_lookup_value){ $data['Price'] = ''; }
	$data['Pages'] = makeSafe($_REQUEST['Pages']);
		if($data['Pages'] == empty_lookup_value){ $data['Pages'] = ''; }
	$data['Publisher'] = makeSafe($_REQUEST['Publisher']);
		if($data['Publisher'] == empty_lookup_value){ $data['Publisher'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: books_before_update
	if(function_exists('books_before_update')){
		$args=array();
		if(!books_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `books` set       `ISBN_NO`=' . (($data['ISBN_NO'] !== '' && $data['ISBN_NO'] !== NULL) ? "'{$data['ISBN_NO']}'" : 'NULL') . ', `Book_Title`=' . (($data['Book_Title'] !== '' && $data['Book_Title'] !== NULL) ? "'{$data['Book_Title']}'" : 'NULL') . ', `Book_Type`=' . (($data['Book_Type'] !== '' && $data['Book_Type'] !== NULL) ? "'{$data['Book_Type']}'" : 'NULL') . ', `Author_Name`=' . (($data['Author_Name'] !== '' && $data['Author_Name'] !== NULL) ? "'{$data['Author_Name']}'" : 'NULL') . ', `Quantity`=' . (($data['Quantity'] !== '' && $data['Quantity'] !== NULL) ? "'{$data['Quantity']}'" : 'NULL') . ', `Purchase_Date`=' . (($data['Purchase_Date'] !== '' && $data['Purchase_Date'] !== NULL) ? "'{$data['Purchase_Date']}'" : 'NULL') . ', `Edition`=' . (($data['Edition'] !== '' && $data['Edition'] !== NULL) ? "'{$data['Edition']}'" : 'NULL') . ', `Price`=' . (($data['Price'] !== '' && $data['Price'] !== NULL) ? "'{$data['Price']}'" : 'NULL') . ', `Pages`=' . (($data['Pages'] !== '' && $data['Pages'] !== NULL) ? "'{$data['Pages']}'" : 'NULL') . ', `Publisher`=' . (($data['Publisher'] !== '' && $data['Publisher'] !== NULL) ? "'{$data['Publisher']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="books_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: books_after_update
	if(function_exists('books_after_update')){
		$res = sql("SELECT * FROM `books` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!books_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='books' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function books_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('books');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_Book_Type = thisOr(undo_magic_quotes($_REQUEST['filterer_Book_Type']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Book_Type
	$combo_Book_Type = new DataCombo;
	// combobox: Purchase_Date
	$combo_Purchase_Date = new DateCombo;
	$combo_Purchase_Date->DateFormat = "mdy";
	$combo_Purchase_Date->MinYear = 1900;
	$combo_Purchase_Date->MaxYear = 2100;
	$combo_Purchase_Date->DefaultDate = parseMySQLDate('1', '1');
	$combo_Purchase_Date->MonthNames = $Translation['month names'];
	$combo_Purchase_Date->NamePrefix = 'Purchase_Date';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='books' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='books' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `books` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'books_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_Book_Type->SelectedData = $row['Book_Type'];
		$combo_Purchase_Date->DefaultDate = $row['Purchase_Date'];
	}else{
		$combo_Book_Type->SelectedData = $filterer_Book_Type;
	}
	$combo_Book_Type->HTML = '<span id="Book_Type-container' . $rnd1 . '"></span><input type="hidden" name="Book_Type" id="Book_Type' . $rnd1 . '" value="' . html_attr($combo_Book_Type->SelectedData) . '">';
	$combo_Book_Type->MatchText = '<span id="Book_Type-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Book_Type" id="Book_Type' . $rnd1 . '" value="' . html_attr($combo_Book_Type->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Book_Type__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Book_Type'] : $filterer_Book_Type); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(Book_Type_reload__RAND__) == 'function') Book_Type_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Book_Type_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#Book_Type-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Book_Type__RAND__.value, t: 'books', f: 'Book_Type' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Book_Type"]').val(resp.results[0].id);
							$j('[id=Book_Type-container-readonly__RAND__]').html('<span id="Book_Type-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Types_view_parent]').hide(); }else{ $j('.btn[id=Types_view_parent]').show(); }


							if(typeof(Book_Type_update_autofills__RAND__) == 'function') Book_Type_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'books', f: 'Book_Type' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_Book_Type__RAND__.value = e.added.id;
				AppGini.current_Book_Type__RAND__.text = e.added.text;
				$j('[name="Book_Type"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Types_view_parent]').hide(); }else{ $j('.btn[id=Types_view_parent]').show(); }


				if(typeof(Book_Type_update_autofills__RAND__) == 'function') Book_Type_update_autofills__RAND__();
			});

			if(!$j("#Book_Type-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Book_Type__RAND__.value, t: 'books', f: 'Book_Type' },
					success: function(resp){
						$j('[name="Book_Type"]').val(resp.results[0].id);
						$j('[id=Book_Type-container-readonly__RAND__]').html('<span id="Book_Type-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Types_view_parent]').hide(); }else{ $j('.btn[id=Types_view_parent]').show(); }

						if(typeof(Book_Type_update_autofills__RAND__) == 'function') Book_Type_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Book_Type__RAND__.value, t: 'books', f: 'Book_Type' },
				success: function(resp){
					$j('[id=Book_Type-container__RAND__], [id=Book_Type-container-readonly__RAND__]').html('<span id="Book_Type-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Types_view_parent]').hide(); }else{ $j('.btn[id=Types_view_parent]').show(); }

					if(typeof(Book_Type_update_autofills__RAND__) == 'function') Book_Type_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/books_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/books_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Book details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return books_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return books_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return books_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#ISBN_NO').replaceWith('<div class=\"form-control-static\" id=\"ISBN_NO\">' + (jQuery('#ISBN_NO').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Book_Title').replaceWith('<div class=\"form-control-static\" id=\"Book_Title\">' + (jQuery('#Book_Title').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Book_Type').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Book_Type_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Author_Name').replaceWith('<div class=\"form-control-static\" id=\"Author_Name\">' + (jQuery('#Author_Name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Quantity').replaceWith('<div class=\"form-control-static\" id=\"Quantity\">' + (jQuery('#Quantity').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Purchase_Date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Purchase_DateDay, #Purchase_DateMonth, #Purchase_DateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Edition').replaceWith('<div class=\"form-control-static\" id=\"Edition\">' + (jQuery('#Edition').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Price').replaceWith('<div class=\"form-control-static\" id=\"Price\">' + (jQuery('#Price').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Pages').replaceWith('<div class=\"form-control-static\" id=\"Pages\">' + (jQuery('#Pages').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Publisher').replaceWith('<div class=\"form-control-static\" id=\"Publisher\">' + (jQuery('#Publisher').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Book_Type)%%>', $combo_Book_Type->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Book_Type)%%>', $combo_Book_Type->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Book_Type)%%>', urlencode($combo_Book_Type->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Purchase_Date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Purchase_Date->GetHTML(true) . '</div>' : $combo_Purchase_Date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Purchase_Date)%%>', $combo_Purchase_Date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'Book_Type' => array('Types', 'Book Type'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ISBN_NO)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Book_Title)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Book_Type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Author_Name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Quantity)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Purchase_Date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Edition)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Price)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Pages)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Publisher)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ISBN_NO)%%>', safe_html($urow['ISBN_NO']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ISBN_NO)%%>', html_attr($row['ISBN_NO']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ISBN_NO)%%>', urlencode($urow['ISBN_NO']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Book_Title)%%>', safe_html($urow['Book_Title']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Book_Title)%%>', html_attr($row['Book_Title']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Book_Title)%%>', urlencode($urow['Book_Title']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Book_Type)%%>', safe_html($urow['Book_Type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Book_Type)%%>', html_attr($row['Book_Type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Book_Type)%%>', urlencode($urow['Book_Type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Author_Name)%%>', safe_html($urow['Author_Name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Author_Name)%%>', html_attr($row['Author_Name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Author_Name)%%>', urlencode($urow['Author_Name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Quantity)%%>', safe_html($urow['Quantity']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Quantity)%%>', html_attr($row['Quantity']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Quantity)%%>', urlencode($urow['Quantity']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Purchase_Date)%%>', @date('m/d/Y', @strtotime(html_attr($row['Purchase_Date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Purchase_Date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['Purchase_Date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Edition)%%>', safe_html($urow['Edition']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Edition)%%>', html_attr($row['Edition']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Edition)%%>', urlencode($urow['Edition']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Price)%%>', safe_html($urow['Price']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Price)%%>', html_attr($row['Price']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Price)%%>', urlencode($urow['Price']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Pages)%%>', safe_html($urow['Pages']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Pages)%%>', html_attr($row['Pages']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Pages)%%>', urlencode($urow['Pages']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Publisher)%%>', safe_html($urow['Publisher']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Publisher)%%>', html_attr($row['Publisher']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Publisher)%%>', urlencode($urow['Publisher']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ISBN_NO)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ISBN_NO)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Book_Title)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Book_Title)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Book_Type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Book_Type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Author_Name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Author_Name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Quantity)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Quantity)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Purchase_Date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Purchase_Date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Edition)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Edition)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Price)%%>', '0.00', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Price)%%>', urlencode('0.00'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Pages)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Pages)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Publisher)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Publisher)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('books');
	if($selected_id){
		$jdata = get_joined_record('books', $selected_id);
		if($jdata === false) $jdata = get_defaults('books');
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata))
	);
	$templateCode .= loadView('books-ajax-cache', $cache_data);

	// hook: books_dv
	if(function_exists('books_dv')){
		$args=array();
		books_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>