<?php

// Data functions (insert, update, delete, form) for table NewsPapers

// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

function NewsPapers_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('NewsPapers');
	if(!$arrPerm[1]){
		return false;
	}

	$data['Language'] = makeSafe($_REQUEST['Language']);
		if($data['Language'] == empty_lookup_value){ $data['Language'] = ''; }
	$data['Name'] = makeSafe($_REQUEST['Name']);
		if($data['Name'] == empty_lookup_value){ $data['Name'] = ''; }
	$data['Date_Of_Receipt'] = intval($_REQUEST['Date_Of_ReceiptYear']) . '-' . intval($_REQUEST['Date_Of_ReceiptMonth']) . '-' . intval($_REQUEST['Date_Of_ReceiptDay']);
	$data['Date_Of_Receipt'] = parseMySQLDate($data['Date_Of_Receipt'], '');
	$data['Date_Published'] = intval($_REQUEST['Date_PublishedYear']) . '-' . intval($_REQUEST['Date_PublishedMonth']) . '-' . intval($_REQUEST['Date_PublishedDay']);
	$data['Date_Published'] = parseMySQLDate($data['Date_Published'], '');
	$data['Pages'] = makeSafe($_REQUEST['Pages']);
		if($data['Pages'] == empty_lookup_value){ $data['Pages'] = ''; }
	$data['Price'] = makeSafe($_REQUEST['Price']);
		if($data['Price'] == empty_lookup_value){ $data['Price'] = ''; }
	$data['Type'] = makeSafe($_REQUEST['Type']);
		if($data['Type'] == empty_lookup_value){ $data['Type'] = ''; }
	$data['Publisher'] = makeSafe($_REQUEST['Publisher']);
		if($data['Publisher'] == empty_lookup_value){ $data['Publisher'] = ''; }
	if($data['Price'] == '') $data['Price'] = "0.00";

	// hook: NewsPapers_before_insert
	if(function_exists('NewsPapers_before_insert')){
		$args=array();
		if(!NewsPapers_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `NewsPapers` set       `Language`=' . (($data['Language'] !== '' && $data['Language'] !== NULL) ? "'{$data['Language']}'" : 'NULL') . ', `Name`=' . (($data['Name'] !== '' && $data['Name'] !== NULL) ? "'{$data['Name']}'" : 'NULL') . ', `Date_Of_Receipt`=' . (($data['Date_Of_Receipt'] !== '' && $data['Date_Of_Receipt'] !== NULL) ? "'{$data['Date_Of_Receipt']}'" : 'NULL') . ', `Date_Published`=' . (($data['Date_Published'] !== '' && $data['Date_Published'] !== NULL) ? "'{$data['Date_Published']}'" : 'NULL') . ', `Pages`=' . (($data['Pages'] !== '' && $data['Pages'] !== NULL) ? "'{$data['Pages']}'" : 'NULL') . ', `Price`=' . (($data['Price'] !== '' && $data['Price'] !== NULL) ? "'{$data['Price']}'" : 'NULL') . ', `Type`=' . (($data['Type'] !== '' && $data['Type'] !== NULL) ? "'{$data['Type']}'" : 'NULL') . ', `Publisher`=' . (($data['Publisher'] !== '' && $data['Publisher'] !== NULL) ? "'{$data['Publisher']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"NewsPapers_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: NewsPapers_after_insert
	if(function_exists('NewsPapers_after_insert')){
		$res = sql("select * from `NewsPapers` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!NewsPapers_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('NewsPapers', $recID, getLoggedMemberID());

	return $recID;
}

function NewsPapers_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('NewsPapers');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='NewsPapers' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='NewsPapers' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: NewsPapers_before_delete
	if(function_exists('NewsPapers_before_delete')){
		$args=array();
		if(!NewsPapers_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `NewsPapers` where `id`='$selected_id'", $eo);

	// hook: NewsPapers_after_delete
	if(function_exists('NewsPapers_after_delete')){
		$args=array();
		NewsPapers_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='NewsPapers' and pkValue='$selected_id'", $eo);
}

function NewsPapers_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('NewsPapers');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='NewsPapers' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='NewsPapers' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Language'] = makeSafe($_REQUEST['Language']);
		if($data['Language'] == empty_lookup_value){ $data['Language'] = ''; }
	$data['Name'] = makeSafe($_REQUEST['Name']);
		if($data['Name'] == empty_lookup_value){ $data['Name'] = ''; }
	$data['Date_Of_Receipt'] = intval($_REQUEST['Date_Of_ReceiptYear']) . '-' . intval($_REQUEST['Date_Of_ReceiptMonth']) . '-' . intval($_REQUEST['Date_Of_ReceiptDay']);
	$data['Date_Of_Receipt'] = parseMySQLDate($data['Date_Of_Receipt'], '');
	$data['Date_Published'] = intval($_REQUEST['Date_PublishedYear']) . '-' . intval($_REQUEST['Date_PublishedMonth']) . '-' . intval($_REQUEST['Date_PublishedDay']);
	$data['Date_Published'] = parseMySQLDate($data['Date_Published'], '');
	$data['Pages'] = makeSafe($_REQUEST['Pages']);
		if($data['Pages'] == empty_lookup_value){ $data['Pages'] = ''; }
	$data['Price'] = makeSafe($_REQUEST['Price']);
		if($data['Price'] == empty_lookup_value){ $data['Price'] = ''; }
	$data['Type'] = makeSafe($_REQUEST['Type']);
		if($data['Type'] == empty_lookup_value){ $data['Type'] = ''; }
	$data['Publisher'] = makeSafe($_REQUEST['Publisher']);
		if($data['Publisher'] == empty_lookup_value){ $data['Publisher'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: NewsPapers_before_update
	if(function_exists('NewsPapers_before_update')){
		$args=array();
		if(!NewsPapers_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `NewsPapers` set       `Language`=' . (($data['Language'] !== '' && $data['Language'] !== NULL) ? "'{$data['Language']}'" : 'NULL') . ', `Name`=' . (($data['Name'] !== '' && $data['Name'] !== NULL) ? "'{$data['Name']}'" : 'NULL') . ', `Date_Of_Receipt`=' . (($data['Date_Of_Receipt'] !== '' && $data['Date_Of_Receipt'] !== NULL) ? "'{$data['Date_Of_Receipt']}'" : 'NULL') . ', `Date_Published`=' . (($data['Date_Published'] !== '' && $data['Date_Published'] !== NULL) ? "'{$data['Date_Published']}'" : 'NULL') . ', `Pages`=' . (($data['Pages'] !== '' && $data['Pages'] !== NULL) ? "'{$data['Pages']}'" : 'NULL') . ', `Price`=' . (($data['Price'] !== '' && $data['Price'] !== NULL) ? "'{$data['Price']}'" : 'NULL') . ', `Type`=' . (($data['Type'] !== '' && $data['Type'] !== NULL) ? "'{$data['Type']}'" : 'NULL') . ', `Publisher`=' . (($data['Publisher'] !== '' && $data['Publisher'] !== NULL) ? "'{$data['Publisher']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="NewsPapers_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: NewsPapers_after_update
	if(function_exists('NewsPapers_after_update')){
		$res = sql("SELECT * FROM `NewsPapers` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!NewsPapers_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='NewsPapers' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function NewsPapers_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('NewsPapers');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Date_Of_Receipt
	$combo_Date_Of_Receipt = new DateCombo;
	$combo_Date_Of_Receipt->DateFormat = "mdy";
	$combo_Date_Of_Receipt->MinYear = 1900;
	$combo_Date_Of_Receipt->MaxYear = 2100;
	$combo_Date_Of_Receipt->DefaultDate = parseMySQLDate('', '');
	$combo_Date_Of_Receipt->MonthNames = $Translation['month names'];
	$combo_Date_Of_Receipt->NamePrefix = 'Date_Of_Receipt';
	// combobox: Date_Published
	$combo_Date_Published = new DateCombo;
	$combo_Date_Published->DateFormat = "mdy";
	$combo_Date_Published->MinYear = 1900;
	$combo_Date_Published->MaxYear = 2100;
	$combo_Date_Published->DefaultDate = parseMySQLDate('', '');
	$combo_Date_Published->MonthNames = $Translation['month names'];
	$combo_Date_Published->NamePrefix = 'Date_Published';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='NewsPapers' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='NewsPapers' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `NewsPapers` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'NewsPapers_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_Date_Of_Receipt->DefaultDate = $row['Date_Of_Receipt'];
		$combo_Date_Published->DefaultDate = $row['Date_Published'];
	}else{
	}

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
			setTimeout(function(){
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/NewsPapers_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/NewsPapers_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'NewsPaper details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return NewsPapers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return NewsPapers_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return NewsPapers_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#Language').replaceWith('<div class=\"form-control-static\" id=\"Language\">' + (jQuery('#Language').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Name').replaceWith('<div class=\"form-control-static\" id=\"Name\">' + (jQuery('#Name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Date_Of_Receipt').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Date_Of_ReceiptDay, #Date_Of_ReceiptMonth, #Date_Of_ReceiptYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Date_Published').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Date_PublishedDay, #Date_PublishedMonth, #Date_PublishedYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Pages').replaceWith('<div class=\"form-control-static\" id=\"Pages\">' + (jQuery('#Pages').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Price').replaceWith('<div class=\"form-control-static\" id=\"Price\">' + (jQuery('#Price').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Type').replaceWith('<div class=\"form-control-static\" id=\"Type\">' + (jQuery('#Type').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Publisher').replaceWith('<div class=\"form-control-static\" id=\"Publisher\">' + (jQuery('#Publisher').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Date_Of_Receipt)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Date_Of_Receipt->GetHTML(true) . '</div>' : $combo_Date_Of_Receipt->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Date_Of_Receipt)%%>', $combo_Date_Of_Receipt->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(Date_Published)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Date_Published->GetHTML(true) . '</div>' : $combo_Date_Published->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Date_Published)%%>', $combo_Date_Published->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Language)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Date_Of_Receipt)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Date_Published)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Pages)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Price)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Publisher)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Language)%%>', safe_html($urow['Language']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Language)%%>', html_attr($row['Language']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Language)%%>', urlencode($urow['Language']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Name)%%>', safe_html($urow['Name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Name)%%>', html_attr($row['Name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name)%%>', urlencode($urow['Name']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date_Of_Receipt)%%>', @date('m/d/Y', @strtotime(html_attr($row['Date_Of_Receipt']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date_Of_Receipt)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['Date_Of_Receipt'])))), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date_Published)%%>', @date('m/d/Y', @strtotime(html_attr($row['Date_Published']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date_Published)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['Date_Published'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Pages)%%>', safe_html($urow['Pages']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Pages)%%>', html_attr($row['Pages']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Pages)%%>', urlencode($urow['Pages']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Price)%%>', safe_html($urow['Price']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Price)%%>', html_attr($row['Price']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Price)%%>', urlencode($urow['Price']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Type)%%>', safe_html($urow['Type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Type)%%>', html_attr($row['Type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Type)%%>', urlencode($urow['Type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Publisher)%%>', safe_html($urow['Publisher']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Publisher)%%>', html_attr($row['Publisher']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Publisher)%%>', urlencode($urow['Publisher']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Language)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Language)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date_Of_Receipt)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date_Of_Receipt)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Date_Published)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Date_Published)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Pages)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Pages)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Price)%%>', '0.00', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Price)%%>', urlencode('0.00'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Publisher)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Publisher)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('NewsPapers');
	if($selected_id){
		$jdata = get_joined_record('NewsPapers', $selected_id);
		if($jdata === false) $jdata = get_defaults('NewsPapers');
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata))
	);
	$templateCode .= loadView('NewsPapers-ajax-cache', $cache_data);

	// hook: NewsPapers_dv
	if(function_exists('NewsPapers_dv')){
		$args=array();
		NewsPapers_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>