<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Return.php");
	include("$currDir/Return_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Return');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Return";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Return`.`id`" => "id",
		"IF(    CHAR_LENGTH(`books1`.`ISBN_NO`), CONCAT_WS('',   `books1`.`ISBN_NO`), '') /* Book Number */" => "Book_Number",
		"IF(    CHAR_LENGTH(`books1`.`Book_Title`), CONCAT_WS('',   `books1`.`Book_Title`), '') /* Book Title */" => "Book_Title",
		"IF(    CHAR_LENGTH(if(`Book_Issue1`.`Issue_Date`,date_format(`Book_Issue1`.`Issue_Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Book_Issue1`.`Issue_Date`,date_format(`Book_Issue1`.`Issue_Date`,'%m/%d/%Y'),'')), '') /* Issue Date */" => "Issue_Date",
		"IF(    CHAR_LENGTH(if(`Book_Issue1`.`Return_Date`,date_format(`Book_Issue1`.`Return_Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Book_Issue1`.`Return_Date`,date_format(`Book_Issue1`.`Return_Date`,'%m/%d/%Y'),'')), '') /* Due Date */" => "Due_Date",
		"if(`Return`.`Return_Date`,date_format(`Return`.`Return_Date`,'%m/%d/%Y'),'')" => "Return_Date",
		"IF(    CHAR_LENGTH(`Users1`.`Name`), CONCAT_WS('',   `Users1`.`Name`), '') /* Member */" => "Member",
		"IF(    CHAR_LENGTH(`Users1`.`Membership_Number`), CONCAT_WS('',   `Users1`.`Membership_Number`), '') /* Number */" => "Number",
		"`Return`.`Fine`" => "Fine",
		"`Return`.`Status`" => "Status"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Return`.`id`',
		2 => 2,
		3 => 3,
		4 => 'date_format(`Book_Issue1`.`Issue_Date`,\'%m/%d/%Y\')',
		5 => 'date_format(`Book_Issue1`.`Return_Date`,\'%m/%d/%Y\')',
		6 => '`Return`.`Return_Date`',
		7 => '`Users1`.`Name`',
		8 => '`Users1`.`Membership_Number`',
		9 => '`Return`.`Fine`',
		10 => 10
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Return`.`id`" => "id",
		"IF(    CHAR_LENGTH(`books1`.`ISBN_NO`), CONCAT_WS('',   `books1`.`ISBN_NO`), '') /* Book Number */" => "Book_Number",
		"IF(    CHAR_LENGTH(`books1`.`Book_Title`), CONCAT_WS('',   `books1`.`Book_Title`), '') /* Book Title */" => "Book_Title",
		"IF(    CHAR_LENGTH(if(`Book_Issue1`.`Issue_Date`,date_format(`Book_Issue1`.`Issue_Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Book_Issue1`.`Issue_Date`,date_format(`Book_Issue1`.`Issue_Date`,'%m/%d/%Y'),'')), '') /* Issue Date */" => "Issue_Date",
		"IF(    CHAR_LENGTH(if(`Book_Issue1`.`Return_Date`,date_format(`Book_Issue1`.`Return_Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Book_Issue1`.`Return_Date`,date_format(`Book_Issue1`.`Return_Date`,'%m/%d/%Y'),'')), '') /* Due Date */" => "Due_Date",
		"if(`Return`.`Return_Date`,date_format(`Return`.`Return_Date`,'%m/%d/%Y'),'')" => "Return_Date",
		"IF(    CHAR_LENGTH(`Users1`.`Name`), CONCAT_WS('',   `Users1`.`Name`), '') /* Member */" => "Member",
		"IF(    CHAR_LENGTH(`Users1`.`Membership_Number`), CONCAT_WS('',   `Users1`.`Membership_Number`), '') /* Number */" => "Number",
		"`Return`.`Fine`" => "Fine",
		"`Return`.`Status`" => "Status"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Return`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`books1`.`ISBN_NO`), CONCAT_WS('',   `books1`.`ISBN_NO`), '') /* Book Number */" => "Book Number",
		"IF(    CHAR_LENGTH(`books1`.`Book_Title`), CONCAT_WS('',   `books1`.`Book_Title`), '') /* Book Title */" => "Book Title",
		"IF(    CHAR_LENGTH(if(`Book_Issue1`.`Issue_Date`,date_format(`Book_Issue1`.`Issue_Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Book_Issue1`.`Issue_Date`,date_format(`Book_Issue1`.`Issue_Date`,'%m/%d/%Y'),'')), '') /* Issue Date */" => "Issue Date",
		"IF(    CHAR_LENGTH(if(`Book_Issue1`.`Return_Date`,date_format(`Book_Issue1`.`Return_Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Book_Issue1`.`Return_Date`,date_format(`Book_Issue1`.`Return_Date`,'%m/%d/%Y'),'')), '') /* Due Date */" => "Due Date",
		"`Return`.`Return_Date`" => "Return Date",
		"IF(    CHAR_LENGTH(`Users1`.`Name`), CONCAT_WS('',   `Users1`.`Name`), '') /* Member */" => "Member",
		"IF(    CHAR_LENGTH(`Users1`.`Membership_Number`), CONCAT_WS('',   `Users1`.`Membership_Number`), '') /* Number */" => "Number",
		"`Return`.`Fine`" => "Fine",
		"`Return`.`Status`" => "Status"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Return`.`id`" => "id",
		"IF(    CHAR_LENGTH(`books1`.`ISBN_NO`), CONCAT_WS('',   `books1`.`ISBN_NO`), '') /* Book Number */" => "Book_Number",
		"IF(    CHAR_LENGTH(`books1`.`Book_Title`), CONCAT_WS('',   `books1`.`Book_Title`), '') /* Book Title */" => "Book_Title",
		"IF(    CHAR_LENGTH(if(`Book_Issue1`.`Issue_Date`,date_format(`Book_Issue1`.`Issue_Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Book_Issue1`.`Issue_Date`,date_format(`Book_Issue1`.`Issue_Date`,'%m/%d/%Y'),'')), '') /* Issue Date */" => "Issue_Date",
		"IF(    CHAR_LENGTH(if(`Book_Issue1`.`Return_Date`,date_format(`Book_Issue1`.`Return_Date`,'%m/%d/%Y'),'')), CONCAT_WS('',   if(`Book_Issue1`.`Return_Date`,date_format(`Book_Issue1`.`Return_Date`,'%m/%d/%Y'),'')), '') /* Due Date */" => "Due_Date",
		"if(`Return`.`Return_Date`,date_format(`Return`.`Return_Date`,'%m/%d/%Y'),'')" => "Return_Date",
		"IF(    CHAR_LENGTH(`Users1`.`Name`), CONCAT_WS('',   `Users1`.`Name`), '') /* Member */" => "Member",
		"IF(    CHAR_LENGTH(`Users1`.`Membership_Number`), CONCAT_WS('',   `Users1`.`Membership_Number`), '') /* Number */" => "Number",
		"`Return`.`Fine`" => "Fine",
		"`Return`.`Status`" => "Status"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'Book_Number' => 'Book Number', 'Member' => 'Member');

	$x->QueryFrom = "`Return` LEFT JOIN `Book_Issue` as Book_Issue1 ON `Book_Issue1`.`id`=`Return`.`Book_Number` LEFT JOIN `books` as books1 ON `books1`.`id`=`Book_Issue1`.`Book_Number` LEFT JOIN `Users` as Users1 ON `Users1`.`id`=`Return`.`Member` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Return_view.php";
	$x->RedirectAfterInsert = "Return_view.php?SelectedID=#ID#";
	$x->TableTitle = "Return";
	$x->TableIcon = "resources/table_icons/application_side_expand.png";
	$x->PrimaryKey = "`Return`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Book Number", "Book Title", "Issue Date", "Due Date", "Return Date", "Member", "Number", "Fine", "Status");
	$x->ColFieldName = array('Book_Number', 'Book_Title', 'Issue_Date', 'Due_Date', 'Return_Date', 'Member', 'Number', 'Fine', 'Status');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Return_templateTV.html';
	$x->SelectedTemplate = 'templates/Return_templateTVS.html';
	$x->TemplateDV = 'templates/Return_templateDV.html';
	$x->TemplateDVP = 'templates/Return_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Return`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Return' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Return`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Return' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Return`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Return_init
	$render=TRUE;
	if(function_exists('Return_init')){
		$args=array();
		$render=Return_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Return_header
	$headerCode='';
	if(function_exists('Return_header')){
		$args=array();
		$headerCode=Return_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Return_footer
	$footerCode='';
	if(function_exists('Return_footer')){
		$args=array();
		$footerCode=Return_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>